# Generated by Django 4.0.5 on 2022-06-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='posts/image_post/%Y/%m/%d/'),
        ),
    ]
