# Generated by Django 4.0.5 on 2022-06-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('FW', 'FrameWorks'), ('OT', 'Others')], default='PY', max_length=65),
        ),
    ]
