# Generated by Django 4.0.5 on 2022-07-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('FW', 'FrameWorks'), ('JV', 'Java'), ('OT', 'Others')], default='PY', max_length=65),
        ),
    ]
