# Generated by Django 4.0.5 on 2022-07-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('FW', 'FrameWorks'), ('JV', 'Java'), ('OT', 'Others')], max_length=2, null=True),
        ),
    ]
